### PR TITLE
Tritium: improvements 3

### PR DESCRIPTION
**Pull request by Castux**
Some polish before release:
- central unplayable hex is greyed out for clarity
- custom chat messages

I think that's all now :)

(I don't know why Github shows the entire history of commits. Maybe because it's from a fork? The diff is correct, at any rate.)

### CODE REVIEW

**Comment by ypaul21** [comment]
> (I don't know why Github shows the entire history of commits. Maybe because it's from a fork? The diff is correct, at any rate.)

I think it's because your branch is still ahead compared to develop. You can make the PR cleaner if you merge your branch with upstream/develop before creating your PR.

**Comment by humanat** [comment]
I don't know why you're using a fork, but I think you need to learn a bit about Git before you go blowing up the branches... I can help in #dev-curious.

**Comment by Castux** [comment]
> I think it's because your branch is still ahead compared to develop. You can make the PR cleaner if you merge your branch with upstream/develop before creating your PR.

I definitely kept the branch up to date, but I might not have done a merge just before opening the PR. I'll try that next time!

> I don't know why you're using a fork, but I think you need to learn a bit about Git before you go blowing up the branches... I can help in #dev-curious.

I'm quite proficient with git :) I'm using a fork simply because I don't have write access to the main repo. I think that's a pretty usual workflow for open-source projects?

**Comment by Perlkonig** [comment]
PR from fork is the typical flow, yes. I have no issue adding you to the list of game developers eventually. I just usually wait until a project or two comes through to make sure they understand the basics. In this case, I'm squashing the merges anyway, so I'm not too fussed about how clean they are, as long as they don't conflict.

**Comment by Perlkonig** [comment]
On its way to dev server now.

**Comment by humanat** [comment]
> PR from fork is the typical flow, yes. I have no issue adding you to the list of game developers eventually. I just usually wait until a project or two comes through to make sure they understand the basics. In this case, I'm squashing the merges anyway, so I'm not too fussed about how clean they are, as long as they don't conflict.

Ok, that squash is why the commit hashes are still listed.  Because those hashes aren't on the develop branch in the real repo.

**Comment by Castux** [comment]
Ooh, that makes sense! Well spotted!

**Pull request merged**
