### PR TITLE
Add Halfcut as variant to Clearcut

### PR DESCRIPTION
**Pull request by ypaul21**
Just making some minor tweaks to Clearcut code so that it becomes Halfcut.

### CODE REVIEW

**Comment by ypaul21** [comment]
Mark is requesting for Halfcut to replace Clearcut. Personally, I also think that Halfcut is a more natural game than Clearcut. It would make more sens for Halfcut to be the main game, and Clearcut to be the variant. I'm not sure what's the best course of action here.

**Comment by Perlkonig** [comment]
Give me some time to think about it.

**Comment by Perlkonig** [comment]
I guess what we have to do is add Halfcut as a new, standalone game and add a Clearcut variant to that (hopefully you can just tweak the file you have now and just rename it and update the metadata). Once that's done, I mark Clearcut as experimental and then either go through and hand edit those 9 game records and ratings or just delete them. I guess I can go through and clean up  and delete Binar at the same time while I'm at it.

Thoughts?

**Comment by ypaul21** [comment]
Works for me. I think Halfcut is great, and I would really like to see it with a proper implementation. I can probably make this change tomorrow evening.

I don't know how many people will be up for these games, so for the time being, those very few historical records of Clearcut games are precious. If they can be transferred over to the new Halfcut game, it would be amazing.

**Comment by Perlkonig** [comment]
They can be transferred. It's just a manual process. I'll move them over.

**Pull request closed without merging**
